spring.application.name=sweet_shop

# ===============================
# SERVER
# ===============================
server.port=${PORT:8080}

# ===============================
# DATABASE (PostgreSQL)
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET}
google.client.id=YOUR_GOOGLE_CLIENT_ID
